DROP DATABASE IF EXISTS DBMECANICA;
CREATE DATABASE DBMECANICA;
USE DBMECANICA;
CREATE TABLE MECANICO (
	IDMECANICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	TELEFONE_RESIDENCIAL VARCHAR(15),
	TELEFONE_COMERCIAL VARCHAR(15),
	TELEFONE_RECADO VARCHAR(15)
);
INSERT INTO MECANICO(NOME, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO)VALUES('Guilherme Maril'	, '48 2222 1111', '48 2222 2222', '48 2222 3333');
INSERT INTO MECANICO(NOME, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO)VALUES('Aline Cristina', '48 3322 1111', '48 3322 2222', '48 3322 3333');
INSERT INTO MECANICO(NOME, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO)VALUES('Jerônimo DalaSi'	, '48 4444 1111', '48 4444 2222', '48 4444 3333');
INSERT INTO MECANICO(NOME, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO)VALUES('Thiago Ciello', '48 5555 1111', '48 5555 2222', '48 5555 3333');

CREATE TABLE SERVICO (
	IDSERVICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	VALOR NUMERIC(8,2)
);

INSERT INTO SERVICO (NOME, VALOR)VALUES('RODIZIO DOS PNEUS', '45.00');
INSERT INTO SERVICO (NOME, VALOR)VALUES('BALANCEAMENTO'	, '25.00');
INSERT INTO SERVICO (NOME, VALOR)VALUES('GEOMETRIA', '25.00');
INSERT INTO SERVICO (NOME, VALOR)VALUES('TROCA DE FLUIDO DE FREIO', '50.00');
INSERT INTO SERVICO (NOME, VALOR)VALUES('VERIFICAÇÃO DA SUSPENSÃO', '25.00');
INSERT INTO SERVICO (NOME, VALOR)VALUES('TROCA DE ÓLEO'	, '35.00');
INSERT INTO SERVICO (NOME, VALOR)VALUES('MAO DE OBRA', '50.00');

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	VALOR NUMERIC(8,2)
);
INSERT INTO PRODUTO (NOME, VALOR)VALUES('distribuidor', '190.88');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('farol', '10.00');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('interruptor de farol'	, '25.30');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('interruptor de marcha ré', '25.30');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('lâmpada de direção (seta)', '39.70');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('lâmpada de farol', '15.90');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('bomba de combustível'	, '390.25');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('junta do carter motor', '1099.99');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('junta tampa de válvula', '999.98');
INSERT INTO PRODUTO (NOME, VALOR)VALUES('válvulas', '10.85');

CREATE TABLE PROPRIETARIO (
	IDPROPRIETARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL,
	RG VARCHAR(16),
	LOGRADOURO VARCHAR(100),
	NUMERO VARCHAR(10),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	UF CHAR(2),
	COMPLEMENTO VARCHAR(100),
	DT_NASCIMENTO DATE,
	TELEFONE_RESIDENCIAL VARCHAR(15),
	TELEFONE_COMERCIAL VARCHAR(15),
	TELEFONE_RECADO VARCHAR(15)
);

INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Lucas Logrini', '1111111111', NULL, 'RUA MATHEUS Lorb'	, 26	, 'BEIRA MAR NORTE', 'SÃO JOSÉ', 'SC', NULL, '48 2222 222222', '48 2222 3333', '48 2222 4444', '1985-04-21');
INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Lucas Mellva', '2222222222', NULL, 'AV. Rhuan Rorti', 28, 'BEIRA MAR NORTE'	, 'SÃO JOSÉ', 'SC', NULL, '48 3333 222222', '48 3333 3333', '48 2222 4444', '1983-01-25');
INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Beatriz AlVinO', '3333333333', NULL, 'AV. Rhuan Rorti', 56, 'BEIRA MAR NORTE', 'SÃO JOSÉ', 'SC', NULL, '48 4444 222222', '48 3333 3333', '48 2222 4444', '1984-10-28');
INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Roberto Adez', '4444444444', NULL, 'RUA Paulo Heqt', 19	, 'BEIRA MAR SUL', 'SÃO JOSÉ', 'SC', NULL, '48 5555 222222', '48 3333 3333', '48 2222 4444', '1982-05-19');
INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Pedro Siues', '5555555555', NULL, 'RUA Victoria Cuehler', 27, 'BEIRA MAR SUL', 'SÃO JOSÉ', 'SC', NULL, '48 6666 222222', '48 3333 3333', '48 2222 4444', '1989-05-13');
INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Nathan Sendil', '6666666666', NULL, 'RUA Victoria Cuehler', 1227, 'BEIRA MAR SUL', 'SÃO JOSÉ', 'SC', NULL, '48 7777 222222', '48 3333 3333', '48 2222 4444', '1987-07-07');
INSERT INTO PROPRIETARIO (NOME, CPF, RG, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, TELEFONE_RESIDENCIAL, TELEFONE_COMERCIAL, TELEFONE_RECADO, DT_NASCIMENTO)VALUES('Gabriela Cristina'	, '7777777777', NULL, 'AV João Saebr', 30	, 'BEIRA MAR SUL', 'SÃO JOSÉ', 'SC', NULL, '48 8888 222222', '48 3333 3333', '48 2222 4444', '1988-08-11');

CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPROPRIETARIO INT NOT NULL,
	MARCA VARCHAR(100) NOT NULL,
	MODELO VARCHAR(100) NOT NULL,
	VERSAO VARCHAR(100) NOT NULL,
	ANO_FABRICACAO INT,
	ANO_MODELO INT,
	PLACA CHAR(7),
	CONSTRAINT FK_VEICULO_PROPRIETARIO FOREIGN KEY (IDPROPRIETARIO) REFERENCES PROPRIETARIO (IDPROPRIETARIO)
);



INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Fiat', 'Strada'	, '', 2014, 2014, 'AAA1111' FROM PROPRIETARIO LIMIT 1,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'VW', 'Saveiro', '', 2014, 2014, 'BBB1111' FROM PROPRIETARIO LIMIT 1,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Ford', 'EcoSport', '', 2013, 2014, 'CCC1111' FROM PROPRIETARIO LIMIT 2,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'GM', 'S10', '', 2014, 2014, 'DDD1111' FROM PROPRIETARIO LIMIT 3,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'GM', 'Montana', '', 2014, 2014, 'EEE1111' FROM PROPRIETARIO LIMIT 4,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Renault'	, 'Duster', '', 2014, 2014, 'FFF1111' FROM PROPRIETARIO LIMIT 5,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Toyota', 'Hilux'	, '', 2014, 2014, 'GGG1111' FROM PROPRIETARIO LIMIT 6,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Fiat', 'Fiorino'	, '', 2014, 2014, 'HHH1111' FROM PROPRIETARIO LIMIT 6,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Chevrolet', 'Tracker', '', 2014, 2014, 'III1111' FROM PROPRIETARIO LIMIT 4,1;

INSERT INTO VEICULO(IDPROPRIETARIO, MARCA, MODELO, VERSAO, ANO_FABRICACAO, ANO_MODELO, PLACA)
SELECT IDPROPRIETARIO, 'Ford', 'Ranger', '', 2014, 2014, 'JJJ1111' FROM PROPRIETARIO LIMIT 3,1;

CREATE TABLE ORCAMENTO (
	IDORCAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDMECANICO INT NOT NULL,
	IDVEICULO INT NOT NULL,
	DT_ORCAMENTO DATETIME NOT NULL,
	CONSTRAINT FK_ORCAMENTO_VEICULO FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO),
	CONSTRAINT FK_ORCAMENTO_MECANICO FOREIGN KEY (IDMECANICO) REFERENCES MECANICO (IDMECANICO)
);

INSERT INTO ORCAMENTO(IDMECANICO, IDVEICULO, DT_ORCAMENTO)
SELECT (SELECT IDMECANICO FROM MECANICO LIMIT 0,1), IDVEICULO, DATE_ADD(NOW(), INTERVAL -5 DAY) FROM VEICULO LIMIT 0, 1;

INSERT INTO ORCAMENTO(IDMECANICO, IDVEICULO, DT_ORCAMENTO)
SELECT (SELECT IDMECANICO FROM MECANICO LIMIT 1,1), IDVEICULO, DATE_ADD(NOW(), INTERVAL -37 DAY) FROM VEICULO LIMIT 1, 1;

INSERT INTO ORCAMENTO(IDMECANICO, IDVEICULO, DT_ORCAMENTO)
SELECT (SELECT IDMECANICO FROM MECANICO LIMIT 2,1), IDVEICULO, DATE_ADD(NOW(), INTERVAL -5 DAY) FROM VEICULO LIMIT 1, 1;

INSERT INTO ORCAMENTO(IDMECANICO, IDVEICULO, DT_ORCAMENTO)
SELECT (SELECT IDMECANICO FROM MECANICO LIMIT 3,1), IDVEICULO, DATE_ADD(NOW(), INTERVAL -370 DAY) FROM VEICULO LIMIT 2, 1;

INSERT INTO ORCAMENTO(IDMECANICO, IDVEICULO, DT_ORCAMENTO)
SELECT (SELECT IDMECANICO FROM MECANICO LIMIT 3,1), IDVEICULO, DATE_ADD(NOW(), INTERVAL -30 DAY) FROM VEICULO LIMIT 3, 1;

INSERT INTO ORCAMENTO(IDMECANICO, IDVEICULO, DT_ORCAMENTO)
SELECT (SELECT IDMECANICO FROM MECANICO LIMIT 2,1), IDVEICULO, DATE_ADD(NOW(), INTERVAL -36 DAY) FROM VEICULO LIMIT 4, 1;

CREATE TABLE ITEM_SERVICO (
	IDORCAMENTO INT NOT NULL,
	IDSERVICO INT NOT NULL,
	QTDE INT,
	CONSTRAINT PK_ITEM_SERVICO PRIMARY KEY (IDORCAMENTO, IDSERVICO),
	CONSTRAINT FK_ITEM_SERVICO_ORCAMENTO FOREIGN KEY (IDORCAMENTO) REFERENCES ORCAMENTO (IDORCAMENTO),
	CONSTRAINT FK_ITEM_SERVICO_SERVICO FOREIGN KEY (IDSERVICO) REFERENCES SERVICO (IDSERVICO)
);

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 2,1), 1 FROM ORCAMENTO LIMIT 0, 1;

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 0,1), 1 FROM ORCAMENTO LIMIT 1, 1;

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 1,1), 1 FROM ORCAMENTO LIMIT 1, 1;

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 1,1), 1 FROM ORCAMENTO LIMIT 0, 1;

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 2,1), 1 FROM ORCAMENTO LIMIT 2, 1;

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 3,1), 1 FROM ORCAMENTO LIMIT 4, 1;

INSERT INTO ITEM_SERVICO (IDORCAMENTO, IDSERVICO, QTDE)
SELECT IDORCAMENTO, (SELECT IDSERVICO FROM SERVICO LIMIT 4,1), 1 FROM ORCAMENTO LIMIT 5, 1;


CREATE TABLE ITEM_PRODUTO (
	IDORCAMENTO INT NOT NULL,
	IDPRODUTO INT NOT NULL,
	QTDE INT,
	CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (IDORCAMENTO, IDPRODUTO),
	CONSTRAINT FK_ITEM_PRODUTO_ORCAMENTO FOREIGN KEY (IDORCAMENTO) REFERENCES ORCAMENTO (IDORCAMENTO),
	CONSTRAINT FK_ITEM_PRODUTO_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
);


INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 1,1), 1 FROM ORCAMENTO LIMIT 0, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 0,1), 1 FROM ORCAMENTO LIMIT 1, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 3,1), 1 FROM ORCAMENTO LIMIT 1, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 6,1), 1 FROM ORCAMENTO LIMIT 1, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 1,1), 1 FROM ORCAMENTO LIMIT 1, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 3,1), 1 FROM ORCAMENTO LIMIT 0, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 4,1), 1 FROM ORCAMENTO LIMIT 0, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 1,1), 1 FROM ORCAMENTO LIMIT 2, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 3,1), 1 FROM ORCAMENTO LIMIT 4, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 4,1), 1 FROM ORCAMENTO LIMIT 5, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 3,1), 1 FROM ORCAMENTO LIMIT 5, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 6,1), 1 FROM ORCAMENTO LIMIT 5, 1;

INSERT INTO ITEM_PRODUTO (IDORCAMENTO, IDPRODUTO, QTDE)
SELECT IDORCAMENTO, (SELECT IDPRODUTO FROM PRODUTO LIMIT 5,1), 1 FROM ORCAMENTO LIMIT 5, 1;

-- Questão 01
select
	*
from 
	proprietario
order by
	nome;

-- Questão 02
select
	*
from
	servico
order by
	servico.nome;
    
-- Questão 03
select
	produto.nome,
    produto.valor
from 
	produto
    inner join item_produto on
    produto.idproduto = item_produto.idproduto
order by
	produto.nome;
    
-- Questão 04
select
	veiculo.marca,
	count(veiculo.idveiculo)
from 
	veiculo
group by
	veiculo.marca;
    
-- Questão 05, desafio
select 
	nome,
    dt_nascimento nasc, 
    date_add(dt_nascimento, interval year(now()) - year(dt_nascimento) year) as niver
from 
	proprietario
where
	date_add(dt_nascimento, interval year(now()) - year(dt_nascimento) year) 
    between now() and date_add(now(), interval 45 day)
order by
		niver;

-- Questão 06
SELECT 
	PROPRIETARIO.IDPROPRIETARIO
    , PROPRIETARIO.NOME
    , VEICULO.MARCA
    , VEICULO.MODELO
    , VEICULO.PLACA
FROM
	PROPRIETARIO
    LEFT JOIN VEICULO ON
    PROPRIETARIO.IDPROPRIETARIO = VEICULO.IDPROPRIETARIO;

-- Questão 07
select
	proprietario.nome,
    veiculo.marca,
    veiculo.modelo,
    veiculo.placa
from
	proprietario
    inner join veiculo on
    proprietario.idproprietario = veiculo.idproprietario;

-- Questão 08
select * from mecanico;

-- Questão 09
select distinct
	produto.idproduto,
	produto.nome,
    produto.valor
from 
	produto
    inner join item_produto on
    produto.idproduto = item_produto.idproduto;

-- Questão 10
select
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    orcamento.idorcamento,
    orcamento.dt_orcamento,
    sum(item_servico.qtde) qtde,
    sum(servico.valor * item_servico.qtde) total
from
	veiculo
    inner join orcamento on
    orcamento.idveiculo = veiculo.idveiculo
    inner join item_servico on
    orcamento.idorcamento = item_servico.idorcamento
    inner join servico on
    servico.idservico = item_servico.idservico
where
	veiculo.idveiculo = 4 -- Troquei pois o veículo 3 não possui servico
group by
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    orcamento.idorcamento,
    orcamento.dt_orcamento;

select * from item_servico where idorcamento = 4;
select * from item_produto where idorcamento = 4;

-- Questão 11
select
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    orcamento.idorcamento,
    orcamento.dt_orcamento,
    sum(item_produto.qtde) qtde,
    sum(item_produto.qtde * produto.valor) total
from
	veiculo
    inner join orcamento on
    orcamento.idveiculo = veiculo.idveiculo
    inner join item_produto on
    orcamento.idorcamento = item_produto.idorcamento
    inner join produto on
    produto.idproduto = item_produto.idproduto
where
	veiculo.idveiculo = 2
group by
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    orcamento.idorcamento,
    orcamento.dt_orcamento;


-- Questão 12
select
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    orcamento.idorcamento,
    orcamento.dt_orcamento,
    mecanico.nome
from
	veiculo
    inner join orcamento on
    veiculo.idveiculo = orcamento.idveiculo
    inner join mecanico on
	mecanico.idmecanico = orcamento.idmecanico;
    
-- Questão 13
select
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    veiculo.ano_fabricacao,
    count(orcamento.idorcamento) qtde
from
	veiculo
    inner join orcamento on
    veiculo.idveiculo = orcamento.idveiculo
where
	veiculo.ano_fabricacao = 2014
group by
	veiculo.marca,
    veiculo.modelo,
    veiculo.placa,
    veiculo.ano_fabricacao;
	

-- Questão 14 e 15, desafio
-- ORCAMENTO 2 S:70.00 + P:616.43 TOTAL: 686,43
SELECT 
	YEAR(ORCAMENTO.DT_ORCAMENTO)
	, MONTH(ORCAMENTO.DT_ORCAMENTO)
    , SUM(TOTAL)
FROM
	(   		
		SELECT
			ITEM_SERVICO.IDORCAMENTO
			, SUM(ITEM_SERVICO.QTDE * SERVICO.VALOR) AS TOTAL
			, 'SERVICO' AS TIPO
		FROM 
			ITEM_SERVICO
			INNER JOIN SERVICO ON
			SERVICO.IDSERVICO = ITEM_SERVICO.IDSERVICO
		GROUP BY
			ITEM_SERVICO.IDORCAMENTO
			
		UNION ALL

		SELECT
			ITEM_PRODUTO.IDORCAMENTO
			, SUM(ITEM_PRODUTO.QTDE * PRODUTO.VALOR) AS TOTAL
			, 'PRODUTO' AS TIPO
		FROM 
			ITEM_PRODUTO
			INNER JOIN PRODUTO ON
			PRODUTO.IDPRODUTO = ITEM_PRODUTO.IDPRODUTO
		GROUP BY
			ITEM_PRODUTO.IDORCAMENTO
            
	) AS CONSULTA
    INNER JOIN ORCAMENTO ON
    ORCAMENTO.IDORCAMENTO = CONSULTA.IDORCAMENTO
GROUP BY
	YEAR(ORCAMENTO.DT_ORCAMENTO)
    , MONTH(ORCAMENTO.DT_ORCAMENTO);