-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO11;
-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO11;
-- CONECTANDO A BASE DE DADOS
USE DBEXERCICIO11;

-- CRIANDO AS TABELAS
CREATE TABLE TITULAR (
	IDTITULAR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , CPF CHAR(11)
	, PRIMARY KEY (IDTITULAR)
);

CREATE TABLE DEPENDENTE (
	IDDEPENDENTE INT NOT NULL AUTO_INCREMENT
    , IDTITULAR INT NOT NULL
    , NOME VARCHAR(100)
    , DTNASCIMENTO DATE
    , PRIMARY KEY (IDDEPENDENTE)
    , FOREIGN KEY (IDTITULAR) REFERENCES TITULAR (IDTITULAR)
);
