-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO15;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO15;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO15;

-- CRIANDO TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , CNH INT
    , CPF CHAR(11)
    , EMAIL VARCHAR(150)
    , CELULAR VARCHAR(15)
    , DDD_CELULAR INT
    , RESIDENCIA VARCHAR(15)
    , DDD_RESIDENCIA INT
    , CONTATO VARCHAR(15)
    , DDD_CONTATO INT
    , RUA VARCHAR(100)
    , NUMERO INT
    , COMPLEMENTO VARCHAR(100)
    , BAIRRO VARCHAR(100)
    , CIDADE VARCHAR(100)
    , ESTADO CHAR(2)
    , CEP CHAR(8)
    , PRIMARY KEY (IDCLIENTE)    
);

CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL AUTO_INCREMENT
    , MARCA VARCHAR(100)
    , MODELO VARCHAR(100)
    , ANO_FABRICACAO INT
    , ANO_MODELO INT
    , TIPO_COMBUSTIVEL ENUM('DISEL', 'FLEX','GASOLINA', 'ALCOO', 'GNV', 'ELETRICO')
    , PRIMARY KEY (IDVEICULO)
);

CREATE TABLE LOCACAO  (
	IDLOCACAO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , IDVEICULO INT NOT NULL
    , DTLOCACAO DATETIME
    , DTENTREGA DATETIME
    , KMLOCACAO INT
    , KMENTREGA INT
    , PRIMARY KEY (IDLOCACAO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO) 
);

CREATE TABLE OPCIONAL (
	IDOPCIONAL INT NOT NULL AUTO_INCREMENT
    , DESCRICAO VARCHAR(100)
    , PRIMARY KEY (IDOPCIONAL)
);

CREATE TABLE CONTEM (
	IDVEICULO INT NOT NULL
    , IDOPCIONAL INT NOT NULL
    , PRIMARY KEY (IDVEICULO, IDOPCIONAL)
    , FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO)
    , FOREIGN KEY (IDOPCIONAL) REFERENCES OPCIONAL (IDOPCIONAL)
);
