SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCOPIASEGURANCA;
CREATE DATABASE DBCOPIASEGURANCA;

USE DBCOPIASEGURANCA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, DT_NASCIMENTO DATE
	, CPF CHAR(11)
	, CIDADE VARCHAR(100)
	, ESTADO CHAR(2)
);

CREATE TABLE HISTORICO_CLIENTE (
	IDHISTORICO INT NOT NULL AUTO_INCREMENT
    , ACAO VARCHAR(15)
    , DTACAO DATETIME
	, IDCLIENTE_ANTES INT 
	, IDCLIENTE_DEPOIS INT 
	, NOME_ANTES VARCHAR(100)
	, NOME_DEPOIS VARCHAR(100)
	, DT_NASCIMENTO_ANTES DATE
	, DT_NASCIMENTO_DEPOIS DATE
	, CPF_ANTES CHAR(11)
	, CPF_DEPOIS CHAR(11)
	, CIDADE_ANTES VARCHAR(100)
	, CIDADE_DEPOIS VARCHAR(100)
	, ESTADO_ANTES CHAR(2)
	, ESTADO_DEPOIS CHAR(2)
    , PRIMARY KEY (IDHISTORICO)
);

DELIMITER $$

CREATE TRIGGER TR_INSERT_CLIENTE AFTER INSERT ON CLIENTE FOR EACH ROW
BEGIN

	INSERT INTO HISTORICO_CLIENTE(ACAO, DTACAO, IDCLIENTE_DEPOIS, NOME_DEPOIS, DT_NASCIMENTO_DEPOIS, CPF_DEPOIS, CIDADE_DEPOIS, ESTADO_DEPOIS)
	VALUES ('INSERT', NOW(), NEW.IDCLIENTE, NEW.NOME, NEW.DT_NASCIMENTO, NEW.CPF, NEW.CIDADE, NEW.ESTADO);
    
END $$

CREATE TRIGGER TR_UPDATE_CLIENTE AFTER UPDATE ON CLIENTE FOR EACH ROW
BEGIN

	INSERT INTO HISTORICO_CLIENTE(ACAO, DTACAO, IDCLIENTE_DEPOIS, NOME_DEPOIS, DT_NASCIMENTO_DEPOIS, CPF_DEPOIS, CIDADE_DEPOIS, ESTADO_DEPOIS, IDCLIENTE_ANTES, NOME_ANTES, DT_NASCIMENTO_ANTES, CPF_ANTES, CIDADE_ANTES, ESTADO_ANTES)
	VALUES ('UPDATE', NOW(), NEW.IDCLIENTE, NEW.NOME, NEW.DT_NASCIMENTO, NEW.CPF, NEW.CIDADE, NEW.ESTADO, OLD.IDCLIENTE, OLD.NOME, OLD.DT_NASCIMENTO, OLD.CPF, OLD.CIDADE, OLD.ESTADO);

END $$


CREATE TRIGGER TR_DELETE_CLIENTE AFTER DELETE ON CLIENTE FOR EACH ROW
BEGIN

	INSERT INTO HISTORICO_CLIENTE(ACAO, DTACAO, IDCLIENTE_ANTES, NOME_ANTES, DT_NASCIMENTO_ANTES, CPF_ANTES, CIDADE_ANTES, ESTADO_ANTES)
	VALUES ('DELETE', NOW(), OLD.IDCLIENTE, OLD.NOME, OLD.DT_NASCIMENTO, OLD.CPF, OLD.CIDADE, OLD.ESTADO);
    
END $$


DELIMITER ;

SELECT * FROM CLIENTE;
SELECT * FROM HISTORICO_CLIENTE;

INSERT INTO CLIENTE(NOME)VALUES('ANDRE');
UPDATE CLIENTE SET NOME = 'MARIA', CIDADE = 'SAO JOSE';

 DELETE FROM CLIENTE;