SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCOPIASEGURANCA;
CREATE DATABASE DBCOPIASEGURANCA;

USE DBCOPIASEGURANCA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, DT_NASCIMENTO DATE
	, CPF CHAR(11)
	, CIDADE VARCHAR(100)
	, ESTADO CHAR(2)
);

CREATE TABLE HISTORICO (
	IDHISTORICO INT NOT NULL AUTO_INCREMENT
    , ACAO VARCHAR(15)
    , DTACAO DATETIME
    , TABELA VARCHAR(45)
    , PRIMARY KEY (IDHISTORICO)
);

CREATE TABLE ITEM_HISTORICO (
	IDITEM INT NOT NULL AUTO_INCREMENT
    , IDHISTORICO INT NOT NULL
    , CAMPO VARCHAR(100)
    , VALOR_ANTES VARCHAR(200)
    , VALOR_DEPOIS VARCHAR(200)
    , PRIMARY KEY (IDITEM)
    , FOREIGN KEY (IDHISTORICO)REFERENCES HISTORICO(IDHISTORICO)
);


DELIMITER $$

CREATE TRIGGER TR_INSERT_CLIENTE AFTER INSERT ON CLIENTE FOR EACH ROW
BEGIN

	DECLARE vIDHISTORICO INT;
    
	INSERT INTO HISTORICO(ACAO, DTACAO, TABELA)
	VALUES ('INSERT', NOW(), 'CLIENTE');
   
   SET vIDHISTORICO = LAST_INSERT_ID();
   
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'IDCLIENTE', NEW.IDCLIENTE);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'NOME', NEW.NOME);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'DT_NASCIMENTO', NEW.DT_NASCIMENTO);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'CPF', NEW.CPF);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'CIDADE', NEW.CIDADE);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'ESTADO', NEW.ESTADO);
   
END $$

CREATE TRIGGER TR_DELETE_CLIENTE AFTER DELETE ON CLIENTE FOR EACH ROW
BEGIN

	DECLARE vIDHISTORICO INT;
    
	INSERT INTO HISTORICO(ACAO, DTACAO, TABELA)
	VALUES ('DELETE', NOW(), 'CLIENTE');
   
   SET vIDHISTORICO = LAST_INSERT_ID();
   
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES)VALUES(vIDHISTORICO, 'IDCLIENTE', OLD.IDCLIENTE);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES)VALUES(vIDHISTORICO, 'NOME', OLD.NOME);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES)VALUES(vIDHISTORICO, 'DT_NASCIMENTO', OLD.DT_NASCIMENTO);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES)VALUES(vIDHISTORICO, 'CPF', OLD.CPF);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES)VALUES(vIDHISTORICO, 'CIDADE', OLD.CIDADE);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES)VALUES(vIDHISTORICO, 'ESTADO', OLD.ESTADO);
   
END $$


CREATE TRIGGER TR_UPDATE_CLIENTE AFTER UPDATE ON CLIENTE FOR EACH ROW
BEGIN

	DECLARE vIDHISTORICO INT;
    
	INSERT INTO HISTORICO(ACAO, DTACAO, TABELA)
	VALUES ('UPDATE', NOW(), 'CLIENTE');
   
   SET vIDHISTORICO = LAST_INSERT_ID();
   
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'IDCLIENTE', OLD.IDCLIENTE, NEW.IDCLIENTE);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'NOME', OLD.NOME, NEW.NOME);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'DT_NASCIMENTO', OLD.DT_NASCIMENTO, NEW.DT_NASCIMENTO);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'CPF', OLD.CPF, NEW.CPF);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'CIDADE', OLD.CIDADE, NEW.CIDADE);
   INSERT INTO ITEM_HISTORICO (IDHISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)VALUES(vIDHISTORICO, 'ESTADO', OLD.ESTADO, NEW.ESTADO);
   
END $$

DELIMITER ;

SELECT * FROM CLIENTE;
SELECT * FROM HISTORICO;
SELECT * FROM ITEM_HISTORICO;
INSERT INTO CLIENTE(NOME)VALUES('ANDRE');
UPDATE CLIENTE SET NOME = 'MARIA', CIDADE = 'FLORIANOPOLIS';
DELETE FROM CLIENTE;