-- APAGANDO CASO JÁ EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO04;

-- CRIA A BASE DE DADOS
CREATE DATABASE DBEXERCICIO04;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO04;

-- CRIANDO AS TABELAS
CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(250) NOT NULL
    , AUTO VARCHAR(100)
    , EDITORA VARCHAR(80)
    , ANO_PUBLICACAO INT
    , PRIMARY KEY (IDLIVRO)
);

