-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO10;
-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO10;
-- CONECTANDO A BASE DE DADOS
USE DBEXERCICIO10;

-- CRIANDO AS TABELAS
CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , LOGIN VARCHAR(45) NOT NULL
    , SENHA VARCHAR(45) NOT NULL
    , DTCADASTRO DATE
    , PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE VIDEO (
	IDVIDEO INT NOT NULL AUTO_INCREMENT 
    , TITULO VARCHAR(150)
    , CATEGORIA VARCHAR(45)
    , DTPUBLICACAO DATE
    , PRIMARY KEY (IDVIDEO)
);

CREATE TABLE ACESSAR (
	IDUSUARIO INT NOT NULL
    , IDVIDEO INT NOT NULL
    , PRIMARY KEY (IDUSUARIO, IDVIDEO)
    , FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
    , FOREIGN KEY (IDVIDEO) REFERENCES VIDEO (IDVIDEO)
);