-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO16;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO16;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO16;


-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , EMAIL VARCHAR(100)
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE EVENTO (
	IDEVENTO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , DTEVENTO DATETIME
    , QTDE_PARCIPANTE INT
    , PRIMARY KEY (IDEVENTO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , DESCRICAO VARCHAR(200)
    , PRECO DECIMAL(8,2)
    , PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE ESCOLHER (
	IDEVENTO INT NOT NULL
    , IDPRODUTO INT NOT NULL
	, PRIMARY KEY (IDEVENTO, IDPRODUTO)
    , FOREIGN KEY (IDEVENTO) REFERENCES EVENTO (IDEVENTO)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
);



