DROP DATABASE IF EXISTS DBLOGALTERACAO;
CREATE DATABASE DBLOGALTERACAO;
USE DBLOGALTERACAO;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, DTNASCIMENTO DATE
	, PRIMARY KEY(IDCLIENTE)
);

-- TABELA DE CONTROLE DE ALTERAÇÕES
CREATE TABLE ALTER_CLIENTE(
	IDALTER INT NOT NULL AUTO_INCREMENT,
    ACAO VARCHAR(15),
    DT_ACAO DATETIME,
    USUARIO VARCHAR(200),
    IDCLIENTE_ANTES INT,
    IDCLIENTE_DEPOIS INT,
    NOME_ANTES VARCHAR(100),
    NOME_DEPOIS VARCHAR(100),
    DT_NASC_ANTES DATE,
    DT_NASC_DEPOIS DATE,
    PRIMARY KEY (IDALTER)
);
/*
-- CRIANDO NOVO USUÁRIO
-- CREATE USER 'BRUNO'@'%' IDENTIFIED BY '123456'; 

-- DANDO ACESSO AOS USUÁRIOS
GRANT SELECT, INSERT, UPDATE, DELETE ON DBLOGALTERACAO.* TO 'CARLA', 'ANA', 'ALFREDO', 'BRUNA', 'ADRIANA', 'ANDERSON', 'BRUNO'@'%';
*/
-- CRIANDO TRIGGERS
DELIMITER $$

CREATE TRIGGER TR_AF_INSERT_CLIENTE AFTER INSERT ON CLIENTE FOR EACH ROW
BEGIN
	INSERT INTO ALTER_CLIENTE(ACAO, DT_ACAO, USUARIO, IDCLIENTE_DEPOIS, NOME_DEPOIS, DT_NASC_DEPOIS)
    VALUES('INSERT', NOW(), SESSION_USER(), NEW.IDCLIENTE, NEW.NOME, NEW.DTNASCIMENTO);
END $$

CREATE TRIGGER TR_AF_UPDATE_CLIENTE AFTER UPDATE ON CLIENTE FOR EACH ROW
BEGIN
	INSERT INTO ALTER_CLIENTE(ACAO, DT_ACAO, USUARIO, IDCLIENTE_DEPOIS, NOME_DEPOIS, DT_NASC_DEPOIS, IDCLIENTE_ANTES, NOME_ANTES, DT_NASC_ANTES)
	VALUES ('UPDATE', NOW(), SESSION_USER(), NEW.IDCLIENTE, NEW.NOME, NEW.DTNASCIMENTO, OLD.IDCLIENTE, OLD.NOME, OLD.DTNASCIMENTO);
END $$

CREATE TRIGGER TR_AF_DELETE AFTER DELETE ON CLIENTE FOR EACH ROW
BEGIN
	INSERT INTO ALTER_CLIENTE(ACAO, DT_ACAO, USUARIO, IDCLIENTE_ANTES, NOME_ANTES, DT_NASC_ANTES)
	VALUES ('DELETE', NOW(), SESSION_USER(), OLD.IDCLIENTE, OLD.NOME, OLD.DTNASCIMENTO);
END $$

DELIMITER ;

/*
-- INSERINDO CLIENTES
INSERT INTO CLIENTE(IDCLIENTE, NOME, DTNASCIMENTO)
VALUES(1, 'ANDRÉ', '1988-07-19');
INSERT INTO CLIENTE(IDCLIENTE, NOME, DTNASCIMENTO)
VALUES(2, 'ANDRÉ', '1988-07-19');
INSERT INTO CLIENTE(IDCLIENTE, NOME, DTNASCIMENTO)
VALUES(3, 'ANDRÉ', '1988-07-19');

-- ALTERANDO CLIENTES
UPDATE CLIENTE SET NOME = 'RENAN' WHERE IDCLIENTE = 1;
UPDATE CLIENTE SET DTNASCIMENTO = '2004-02-29' WHERE NOME = 'RENAN';

-- APAGANDO CLIENTES
DELETE FROM CLIENTE WHERE IDCLIENTE = 3; 
*/
-- CONSULTAS
SELECT * FROM CLIENTE;
SELECT * FROM ALTER_CLIENTE;