-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO17;

-- CRIANDO A BASE DE DADOS 
CREATE DATABASE DBEXERCICIO17;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO17;

-- CRIANDO AS TABELAS 
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , DTNASCIMENTO DATE
    , DTCADASTRO DATETIME
    , CPF CHAR(11)
    , RUA VARCHAR(100)
    , NUMERO INT 
    , COMPLEMENTO VARCHAR(100)
    , BAIRRO VARCHAR(100)
    , CIDADE VARCHAR(100)
    , ESTADO CHAR(2)
    , CEP CHAR(8)
    , RESIDENCIAL_NUMERO VARCHAR(10)
    , RESIDENCIAL_DDD INT
    , CELULAR_NUMERO VARCHAR(10)
    , CELULAR_DDD INT
    , REFERENCIA_NOME VARCHAR(45)
    , REFERENCIA_NUMERO VARCHAR(10)
    , REFERENCIA_DDD INT
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE IMOVEL (
	IDIMOVEL INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , DESCRICAO VARCHAR(300)
    , RUA VARCHAR(100)
    , NUMERO INT 
    , COMPLEMENTO VARCHAR(100)
    , BAIRRO VARCHAR(100)
    , CIDADE VARCHAR(100)
    , ESTADO CHAR(2)
    , CEP CHAR(8)
    , VALOR DECIMAL(8,2)
    , PONTOREFERENCIA VARCHAR(100)
    , PRIMARY KEY (IDIMOVEL)
);

CREATE TABLE CARACTERISTICA (
	IDCARACTERISTICA INT  NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , DESCRICAO VARCHAR(100)
    , PRIMARY KEY (IDCARACTERISTICA)
);

CREATE TABLE DETALHE (
	IDIMOVEL INT NOT NULL
    , IDCARACTERISTICA INT NOT NULL
    , VALOR VARCHAR(45)
    , PRIMARY KEY (IDIMOVEL, IDCARACTERISTICA)
    , FOREIGN KEY (IDIMOVEL) REFERENCES IMOVEL (IDIMOVEL)
    , FOREIGN KEY (IDCARACTERISTICA) REFERENCES CARACTERISTICA (IDCARACTERISTICA)
);

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY (IDFUNCIONARIO)
);

CREATE TABLE CONTRATO (
	IDCONTRATO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , IDIMOVEL INT NOT NULL
    , IDFUNCIONARIO INT NOT NULL
    , DTFINANCIAMENTO DATE
    , DTINICIOPAGAMENTO DATE
    , VALOR NUMERIC(8,2)
    , JUROS NUMERIC(8,3)
    , DIAVENDIMENTO INT
    , PRIMARY KEY (IDCONTRATO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IMOVEL) REFERENCES IMOVEL (IDIMOVEL)
    , FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
);

CREATE TABLE PARCELA (
	IDPARCELA INT NOT NULL AUTO_INCREMENT
    , IDCONTRATO INT NOT NULL
    , DTGERACAO DATE
    , DTVENCIMENTO DATE
    , DTPAGAMENTO DATE
    , VALORGERADO NUMERIC(8,2)
    , VALORPAGO NUMERIC(8,2)
    , PRIMARY KEY (IDPARCELA)
    , FOREIGN KEY (IDCONTRATO)REFERENCES CONTRATO (IDCONTRATO)
);