-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO12;
-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO12;
-- CONECTANDO A BASE DE DADOS
USE DBEXERCICIO12;

-- CRIANDO AS TABELAS
CREATE TABLE PACIENTE (
	IDPACIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , TELEFONE VARCHAR(15)
    , RUA VARCHAR(100)
    , NUMERO INT
    , COMPLEMENTO VARCHAR(80)
    , BAIRRO VARCHAR(100)
    , CIDADE VARCHAR(100)
    , ESTADO CHAR(2)
    , CEP CHAR(8)
    , PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE MEDICO (
	IDMEDICO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , CRM INT
    , CELULAR VARCHAR(15)
    , PRIMARY KEY (IDMEDICO)
);

CREATE TABLE CONSULTA (
	IDCONSULTA INT NOT NULL AUTO_INCREMENT
    , DTCONSULTA DATE
    , HRCONSULTA TIME
    , IDPACIENTE INT NOT NULL
    , IDMEDICO INT NOT NULL
    , PRIMARY KEY (IDCONSULTA)
    , FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
    , FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);
