-- APAGANDO A BASE DE DADOS PARA CRIAR NOVAMENTE
DROP DATABASE IF EXISTS DBEXERCICIO03;

-- CRIAR A BASE DE DADOS
CREATE DATABASE DBEXERCICIO03;

-- CONECTANDO NA BASE CRIADA
USE DBEXERCICIO03;

-- CRIANDO AS TABELAS
CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL AUTO_INCREMENT
    , MARCA VARCHAR(50) NOT NULL
    , MODELO VARCHAR(50) NOT NULL
    , ANO_MODELO INT
    , ANO_FABRICACAO INT
    , PLACA VARCHAR(10)
    , COR VARCHAR(30)
    , CHASSI VARCHAR(45)
    , PRIMARY KEY (IDVEICULO)
);





