DROP DATABASE IF EXISTS DBVACINA;
CREATE DATABASE DBVACINA;
USE DBVACINA;

CREATE TABLE COMPRA (
	IDCOMPRA INT NOT NULL AUTO_INCREMENT
    , DTCOMPRA DATE
    , LOTE CHAR(15)
    , QTDE INT
    , INTERVALO INT
    , PRIMARY KEY (IDCOMPRA)
);

CREATE TABLE PACIENTE (
	IDPACIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , DTATENDIMENTO DATE
    , PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT
    , IDCOMPRA INT NOT NULL
    , REGISTRO CHAR(25)
    , IDPACIENTE INT
    , DTAPLICACAO DATE
    , DOSE INT
    , PRIMARY KEY (IDVACINA)
    , FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (IDCOMPRA)
    , FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
);

DELIMITER $$

-- PEGAR A DATA ATUAL
/*
NEW.DTCOMPRA = NOW();

NEW.LOTE = 
YEAR(NOW())
LPAD(MONTH(NOW()), 2, '0')
LPAD(DAY(NOW()), 2, '0')
LPAD(1, 7, '0'))
*/

CREATE TRIGGER TR_BI_COMPRA BEFORE INSERT ON COMPRA FOR EACH ROW
BEGIN
	DECLARE vANO CHAR(4);
    DECLARE vMES CHAR(2);
    DECLARE vDIA CHAR(2);
    DECLARE vID  CHAR(7);
    
	-- CALCULANDO O LOTE
    SET vANO = YEAR(NOW());
    SET vMES = LPAD(MONTH(NOW()), 2, '0');
    SET vDIA = LPAD(DAY(NOW()), 2, '0');
    
	SELECT LPAD(AUTO_INCREMENT, 7, '0') 
    INTO vID
	FROM information_schema.tables 
	WHERE TABLE_SCHEMA = 'DBVACINA' AND TABLE_NAME = 'COMPRA';   

	SET NEW.DTCOMPRA = NOW();
    SET NEW.LOTE = CONCAT(CONCAT(CONCAT(vANO, vMES),vDIA), vID);
    
END $$

CREATE TRIGGER TR_AI_COMPRA AFTER INSERT ON COMPRA FOR EACH ROW
BEGIN

	DECLARE vQTDE INT;
    DECLARE vREGISTRO CHAR(25);
    
    SET vQTDE = 0;
    
    WHILE vQTDE <= NEW.QTDE DO
    
		SET vREGISTRO = CONCAT(NEW.LOTE, LPAD(vQTDE, 10, '0'));
        
		INSERT INTO VACINA (IDCOMPRA, REGISTRO) VALUES (NEW.IDCOMPRA, vREGISTRO);
        
        SET vQTDE = vQTDE + 1; 
    
    END WHILE;

END $$ 

CREATE TRIGGER TR_AF_PACIENTE AFTER INSERT ON PACIENTE FOR EACH ROW
BEGIN

	DECLARE vIDVACINA_1DOSE INT;
    DECLARE vIDVACINA_2DOSE INT;
    DECLARE vINTERVALO INT;
    
    -- PEGANDO A 1 DOSE
	SELECT MIN(IDVACINA) 
	INTO vIDVACINA_1DOSE
	FROM VACINA WHERE IDPACIENTE IS NULL;

	UPDATE VACINA SET 
		IDPACIENTE = NEW.IDPACIENTE
        , DTAPLICACAO = NOW() 
        , DOSE = 1
	WHERE IDVACINA = vIDVACINA_1DOSE;

	-- PEGANDO O INTERVALO
    SELECT COMPRA.INTERVALO 
    INTO vINTERVALO
	FROM
		VACINA
		INNER JOIN COMPRA ON
		COMPRA.IDCOMPRA = VACINA.IDCOMPRA
	WHERE VACINA.IDVACINA = vIDVACINA_1DOSE;

    -- PEGANDO A 2 DOSE
	SELECT MIN(IDVACINA) 
	INTO vIDVACINA_2DOSE
	FROM VACINA WHERE IDPACIENTE IS NULL;

	UPDATE VACINA SET 
		IDPACIENTE = NEW.IDPACIENTE
        , DTAPLICACAO = DATE_ADD(NOW(), INTERVAL vINTERVALO DAY)
        , DOSE = 2
	WHERE IDVACINA = vIDVACINA_2DOSE;
    
END $$

DELIMITER ;


INSERT INTO COMPRA (QTDE, INTERVALO)VALUES(5, 10);
INSERT INTO COMPRA (QTDE, INTERVALO)VALUES(2, 15);
SELECT * FROM COMPRA;
SELECT * FROM VACINA;
SELECT * FROM PACIENTE;

INSERT INTO PACIENTE(NOME)VALUES('ANDRE');