SET GLOBAL log_bin_trust_function_creators = 1;
SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBVACINA;
CREATE DATABASE DBVACINA;
USE DBVACINA;

CREATE TABLE COMPRA (
	IDCOMPRA INT NOT NULL AUTO_INCREMENT
    , DTCOMPRA DATE
    , LOTE CHAR(15)
    , QTDE INT
    , INTERVALO INT
    , PRIMARY KEY (IDCOMPRA)
);

CREATE TABLE PACIENTE (
	IDPACIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , DTATENDIMENTO DATE
    , PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT
    , IDCOMPRA INT NOT NULL
    , REGISTRO CHAR(25)
    , IDPACIENTE INT
    , DTAPLICACAO DATE
    , DOSE INT
    , PRIMARY KEY (IDVACINA)
    , FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (IDCOMPRA)
    , FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
);

DELIMITER $$

CREATE PROCEDURE SP_REGISTRA_COMPRA(pQTDE INT, pINTERVALO INT)
BEGIN
	
	DECLARE vANO CHAR(4);
    DECLARE vMES CHAR(2);
    DECLARE vDIA CHAR(2);
    DECLARE vLOTE_REGISTRO VARCHAR(30);
    DECLARE vIDCOMPRA INT;
    DECLARE vCONTADOR INT;

	-- CALCULANDO O LOTE
    SET vANO = YEAR(NOW());
    SET vMES = LPAD(MONTH(NOW()), 2, '0');
    SET vDIA = LPAD(DAY(NOW()), 2, '0');

	INSERT INTO COMPRA(DTCOMPRA, QTDE, INTERVALO)VALUES(NOW(), pQTDE, pINTERVALO);
	SET vIDCOMPRA = LAST_INSERT_ID();
    SET vLOTE_REGISTRO = CONCAT(CONCAT(CONCAT(vANO, vMES), vDIA), LPAD(vIDCOMPRA, 7, '0'));
    
    UPDATE COMPRA
    SET LOTE = vLOTE_REGISTRO
    WHERE IDCOMPRA = vIDCOMPRA;
    
    SET vCONTADOR = 1;
    WHILE (vCONTADOR <= pQTDE) DO
    
		INSERT INTO VACINA (IDCOMPRA, REGISTRO)VALUES(vIDCOMPRA, CONCAT(vLOTE_REGISTRO, LPAD(vCONTADOR, 10, '0')));
        SET vCONTADOR = vCONTADOR + 1;
        
	END WHILE;
    
END $$

DELIMITER ;

CALL SP_REGISTRA_COMPRA(500, 20);

SELECT * FROM COMPRA;
SELECT * FROM VACINA;


