-- APAGANDO A BASE DE BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO02;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO02;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO02;

-- CRIANDO A TABELA USUARIO
CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30),
    SOBRENOME VARCHAR(40),
    LOGIN VARCHAR(80) UNIQUE,
    SENHA VARCHAR(30),
    SEXO CHAR(1),
    DTNASCIMENTO DATE,
	PRIMARY KEY (IDUSUARIO)
);