-- VERIFICAR SE EXITE E APAGAR
DROP DATABASE IF EXISTS DBEXERCIO01;

-- CRIAR A BASE DE DADOS 
CREATE DATABASE DBEXERCIO01;

-- CONECTAR A BASE DE DADOS
USE DBEXERCIO01;

-- CRIAR A TABELA DE ALUNO
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY (IDALUNO)
);

