SET GLOBAL LOG_BIN_TRUST_FUNCTION_CREATORS = 1;
SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBBARES_E_BANDAS;
CREATE DATABASE DBBARES_E_BANDAS;
USE DBBARES_E_BANDAS;

CREATE TABLE BANDA(
	IDBANDA INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50),
    TELEFONE INT,
    NOME VARCHAR(100),
    SENHA VARCHAR(50),
	DESCRICAO VARCHAR(100),
    ESTILO VARCHAR(100),
    N_INTEGRANTES INT,
    PRIMARY KEY(IDBANDA)
);

CREATE TABLE LOCAL(
	IDLOCAL INT NOT NULL AUTO_INCREMENT,
    ENDERECO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO CHAR(2),
    EMAIL VARCHAR(50),
    TELEFONE INT,
    SENHA VARCHAR(50),
    PRIMARY KEY(IDLOCAL)
);

CREATE TABLE EVENTO(
	IDEVENTO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100),
    DATA_HORA DATETIME,
    VALOR_CACHE INT,
    IDBANDA INT,
    IDLOCAL INT,
    PRIMARY KEY (IDEVENTO),
    FOREIGN KEY(IDBANDA) REFERENCES BANDA(IDBANDA),
    FOREIGN KEY(IDLOCAL) REFERENCES LOCAL(IDLOCAL)
);